### ISSUE TITLE
Getting `look-behind requires fixed-width pattern` error 

### ISSUE THREAD

**Issue by TysonRV** [thinkwelltwd/device_detector#10]
I'm getting `look-behind requires fixed-width pattern` error when literally trying to run the example in the README.

My current Python version is 3.6.8 and my code looks something like this:

```
from device_detector import DeviceDetector

ua = 'Mozilla/5.0 (Linux; Android 4.3; C5502 Build/10.4.1.B.0.101) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.136 Mobile Safari/537.36'

device = DeviceDetector(ua).parse()
```

So, exactly like in the example. The only thing I can think of is the Python version, any idea why this could be colliding somehow? 

I can provide a full stacktrace, but the relevant places seem to be:

> .venv/lib/python3.6/site-packages/device_detector/parser/parser.py in _parse
`73.        for ua_data in self.regex_list: `

> .venv/lib/python3.6/site-packages/device_detector/yaml_loader.py in regex_list
`69.     regex['regex'] = re.compile(BOUNDED_REGEX.format(regex['regex']), re.IGNORECASE) `

I will update my virtualenv with a new python version, just to see what happens. I'll keep you posted

**Comment by thinkwelltwd** [comment]
Oops, I try to catch that error and print out a recommendation to use the regex library. I need to make that a hard dependency.

Do `pip3 install regex` and it should now work.

**Comment by TysonRV** [comment]
Awesome, that solved the problem. Thanks for the prompt response!
