### ISSUE TITLE
is_mobile method check for desktop, instead of mobile OS.

### ISSUE THREAD

**Issue by dmirecki** [thinkwelltwd/device_detector#12]
Hi,

In a os parser there are two methods that look identical: 
```
def is_desktop(self) -> bool:
  return self.family() in self.DESKTOP_OS
```

```
def is_mobile(self) -> bool:
  return self.family() in self.DESKTOP_OS
```

In code: [first method](https://github.com/thinkwelltwd/device_detector/blob/1ae5bde95e0c801f7cc2c2ec045af7017ffc4d74/device_detector/parser/operating_system.py#L165), [second method](https://github.com/thinkwelltwd/device_detector/blob/1ae5bde95e0c801f7cc2c2ec045af7017ffc4d74/device_detector/parser/operating_system.py#L167)

I think that `is_mobile` should check if os is a mobile, instead of a desktop.

**Comment by thinkwelltwd** [comment]
Thanks for the bug report!
