### ISSUE TITLE
The Package identifing galaxy gear as smartphone

### ISSUE THREAD

**Issue by omriten** [thinkwelltwd/device_detector#15]
hey, the useragent "Mozilla/5.0   (Linux; Tizen 2.4; SAMSUNG SM-R760) AppleWebKit/537.3 (KHTML, like Gecko)   SamsungBrowser/1.1 Mobile Safari/537.3'" parsing as smartphone and not as watch.

other than that, great Package. thanks!!!

**Comment by thinkwelltwd** [comment]
As of f61e42bb9, the device type is now classified as `wearable`.
