### ISSUE TITLE
Unable to detect device

### ISSUE THREAD

**Issue by vinodkahuja** [thinkwelltwd/device_detector#16]
device_detector is unable to detect device type for following user agents. 

"Kik/13.0.0.7521 (Android 7.1.1) Mozilla/5.0 (Linux; Android 7.1.1; 6060S Build/NMF26F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.126 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 5.1.1; 2014817 Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.89 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 5.1.1; VS985 4G Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 6.0.1; E0108 Build/MOB30R) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.158 Safari/537.36"
"Mozilla/5.0 (Linux; Android 6.0.1; FP2 Build/FP2-gms-18.04.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.101 Mobile Safari/537.36 (Ecosia android@62.0.3202.101)"
"Mozilla/5.0 (Linux; Android 6.0.1; S60 Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.158 Mobile Safari/537.36"

**Comment by thinkwelltwd** [comment]
> device_detector is unable to detect device type for following user agents.

And I'm not able to tell either. 😉 

Could you please include the device info for each UA string?

**Comment by vinodahujauno** [comment]
I don't know for sure as I got a bunch of data and I am using this library to find the type of device used by each agent in my research. 

I checked these strings on the following site and device type is mobile for all strings.
https://developers.whatismybrowser.com/useragents/parse/#parse-useragent

**Comment by thinkwelltwd** [comment]
As of f61e42bb9, 3 out of the 5 examples above now include device details.
