### ISSUE TITLE
Regularly outputs "xxx does not exist" errors (0.8 from pip)

### ISSUE THREAD

**Issue by adq** [thinkwelltwd/device_detector#20]
Hi, I'm seeing things like the following being printed out all the time:

device_detector/appids/secondary.yml does not exist
device_detector/appdetails/games.yml does not exist
device_detector/appdetails/messaging.yml does not exist
device_detector/appdetails/mobile_apps.yml does not exist
device_detector/appdetails/mediaplayers.yml does not exist
device_detector/appdetails/p2p.yml does not exist
device_detector/appdetails/pim.yml does not exist
device_detector/appdetails/vpnproxy.yml does not exist
device_detector/appdetails/osutility.yml does not exist
device_detector/appdetails/antivirus.yml does not exist
device_detector/appdetails/desktop_apps.yml does not exist
device_detector/appids/secondary.yml does not exist
device_detector/appids/ignored.yml does not exist
device_detector/appids/normalized.yml does not exist

**Comment by adq** [comment]
Hey! I've figured out what is going on. 

Your release tgz on PIP is missing the YAML files from appdetails/appids: setup.py issue?

**Comment by adq** [comment]
Hi, I submitted a pull request fixing the package build. See https://github.com/thinkwelltwd/device_detector/pull/22

**Comment by tarasowski** [comment]
Still not integrated, but anyway there is a workaround: `pip install git+git://github.com/thinkwelltwd/device_detector.git`

**Comment by thinkwelltwd** [comment]
Closed with #22 with thanks to @adq
