### ISSUE TITLE
The following UAs crash the library (0.8 from pip)

### ISSUE THREAD

**Issue by adq** [thinkwelltwd/device_detector#21]
If I decode any of the following UAs, I get the following error: 

> File "/usr/lib/python3.7/site-packages/device_detector/device_detector.py", line 237, in parse
>    self.parse_client()
> File "/usr/lib/python3.7/site-packages/device_detector/device_detector.py", line 267, in parse_client
>    app_id = app_idx.extract().get('app_id', '')
>  File "/usr/lib/python3.7/site-packages/device_detector/parser/extractors.py", line 189, in extract
>    details = self.normalized_app_ids().get(app_id.lower(), {'app_id': app_id})
>AttributeError: 'list' object has no attribute 'get'

Example UAs causing this:
> IMAtvOS/t.3.8.0 tvOS/12.3 com.wetv.WEtviPhoneApp/2.0.94
> tv.accedo.hgtv/3.3.1 (Linux;Android 5.1.1) ExoPlayerLib/2.5.4
> com.hgtv.watcher/3.4.3 (Linux;Android 8.0.0) ExoPlayerLib/2.5.4
> tv.accedo.foodnetwork/3.4.3 (Linux;Android 5.1.1) ExoPlayerLib/2.5.4

Example code:

>>> from device_detector import DeviceDetector
>>> d = DeviceDetector('IMAtvOS/t.3.8.0 tvOS/12.3 com.wetv.WEtviPhoneApp/2.0.94').parse()
device_detector/appids/secondary.yml does not exist
device_detector/appids/ignored.yml does not exist
device_detector/appids/normalized.yml does not exist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/device_detector/device_detector.py", line 237, in parse
    self.parse_client()
  File "/usr/lib/python3.7/site-packages/device_detector/device_detector.py", line 267, in parse_client
    app_id = app_idx.extract().get('app_id', '')
  File "/usr/lib/python3.7/site-packages/device_detector/parser/extractors.py", line 189, in extract
    details = self.normalized_app_ids().get(app_id.lower(), {'app_id': app_id})
AttributeError: 'list' object has no attribute 'get'
>>>

**Comment by thinkwelltwd** [comment]
Should be fixed with your PR #22
