### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by mormalca** [thinkwelltwd/device_detector#28]
I am trying to use the dvice detactor parser in this way:

```
from device_detector import DeviceDetector

 ua = 'Mozilla/5.0 (Linux; Android 6.0; 4Good Light A103 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Mobile Safari/537.36'
device = DeviceDetector(ua).parse()
```
and I'm getting the following issue :

```
 return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8a in position 10570: character maps to <undefined>
```
someone have any idea what could be the issue?

thanks

**Comment by thinkwelltwd** [comment]
What version of Python are you using, and on what platform?

**Comment by mormalca** [comment]
I use Python3.8 on pycharm

**Comment by thinkwelltwd** [comment]
By platform, I meant what operating system, rather than IDE.

It's working for me on Python3.8 in Linux Mint 19. At this point, I'm going to close the ticket as I can't duplicate it.
