### ISSUE TITLE
No licence in repo

### ISSUE THREAD

**Issue by jonathaneeckhout** [thinkwelltwd/device_detector#34]
This repo is missing a licence.

The parent repo however has a GNU licence.

https://github.com/matomo-org/device-detector/blob/master/LICENSE

Is it possible to add the same licence?

Thanks

**Comment by thinkwelltwd** [comment]
https://github.com/thinkwelltwd/device_detector/blob/master/device_detector/LICENSE

**Comment by jonathaneeckhout** [comment]
Thanks for verification
