### ISSUE TITLE
Question about yml updates

### ISSUE THREAD

**Issue by pierrocknroll** [thinkwelltwd/device_detector#4]
Hello (it's me again),

Since your lib is a port of an original project, how do you manage if this project updates the regexes in the yml files ? Your yml files will be outdated ?
Is this somehow possible to include most up to date files ?
Thanks

**Comment by thinkwelltwd** [comment]
At this point I plan to manually port changes over. if there's a change you want, feel free to make a PR.

**Comment by pierrocknroll** [comment]
Hello,
I tried to add the lasts regexs from the original package in your regexs directory and I have some questions :
- Do you think it's a good idea ?
- Why there are some yml files in your package that does not exist in the original ? For exemple, antivirus.yml. I think it will be more maintainable if the directory structures are the same, no ?

**Comment by thinkwelltwd** [comment]
> Do you think it's a good idea ?

Do I think what's a good idea?  Is it a good idea to add regexes and tests? Sure. And send PR of those changes too.

> Why there are some yml files in your package that does not exist in the original ?

Because my primary use case is different. It's scratching my itches. At some point I might rework the directory structure. Or I might not.

If you don't mind my asking, why the stream of questions? Have you ever been negatively impacted by the library or its choices so far?

**Comment by pierrocknroll** [comment]
My question is, do you think it's a good idea to replace directly your regexs by the latest regexs from the original package ?

Don't worry, I like your library a lot. I use it for a very important project and because it's a very young repo, I try to choose very conscientiously and I want the detection the most up to date as possible. I prefer asking this because if your lib becomes dead in the near future, it has to be maintainable.

**Comment by thinkwelltwd** [comment]
> My question is, do you think it's a good idea to replace directly your regexs by the latest regexs from the original package ?

If you don't want any of my changes, yes. If you want my changes, no. Then the more manual step of selecting the updates will need to be chosen.

> I prefer asking this because if your lib becomes dead in the near future, it has to be maintainable.

The entire repo is right here on github, and anyone can help keep it alive via PRs, forks and so on.
