### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by welkensoyo** [thinkwelltwd/device_detector#9]
settings.py has *args before a variable name for the MAX_CACHE_SIZE.  This is breaking import.

**Comment by thinkwelltwd** [comment]
What are you attempting to import that's breaking?

**Comment by dmalis** [comment]
py 2.7 here, just trying out the example code: from device_detector import DeviceDetector

**Comment by thinkwelltwd** [comment]
Ok, that explains it; Python 3+ only supported.
